// <auto-generated />
using System;
using Asada.Infraestructura.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asada.Infraestructura.Migrations
{
    [DbContext(typeof(AsadaDbContext))]
    [Migration("20261009174034_Sprint2Mediciones")]
    partial class Sprint2Mediciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asada.Dominio.Entidades.Abonado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("Correlativo")
                        .HasColumnType("integer")
                        .HasColumnName("correlativo");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("Id")
                        .HasName("pk_abonados");

                    b.HasIndex("OrganizacionId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_abonados_organizacion_id_codigo");

                    b.HasIndex("OrganizacionId", "Correlativo")
                        .IsUnique()
                        .HasDatabaseName("ix_abonados_organizacion_id_correlativo");

                    b.HasIndex("OrganizacionId", "TipoIdentificacion", "Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_abonados_organizacion_id_tipo_identificacion_identificacion");

                    b.ToTable("abonados", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Medicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumo")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaLectura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_lectura");

                    b.Property<decimal>("Lectura")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("lectura");

                    b.Property<int>("MedidorId")
                        .HasColumnType("integer")
                        .HasColumnName("medidor_id");

                    b.Property<string>("MotivosRevision")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("motivos_revision");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    b.Property<bool>("RequiereRevision")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_revision");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("pk_mediciones");

                    b.HasIndex("MedidorId")
                        .HasDatabaseName("ix_mediciones_medidor_id");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_mediciones_organizacion_id");

                    b.HasIndex("PeriodoId")
                        .HasDatabaseName("ix_mediciones_periodo_id");

                    b.HasIndex("ServicioId", "PeriodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_mediciones_servicio_id_periodo_id");

                    b.ToTable("mediciones", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Medidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaInstalacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_instalacion");

                    b.Property<DateOnly?>("FechaRetiro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_retiro");

                    b.Property<decimal?>("LecturaFinal")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("lectura_final");

                    b.Property<decimal>("LecturaInicial")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("lectura_inicial");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_serie");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("pk_medidores");

                    b.HasIndex("OrganizacionId", "NumeroSerie")
                        .IsUnique()
                        .HasDatabaseName("ix_medidores_organizacion_id_numero_serie");

                    b.HasIndex(new[] { "ServicioId" }, "ix_medidores_servicio_id")
                        .HasDatabaseName("ix_medidores_servicio_id");

                    b.HasIndex(new[] { "ServicioId" }, "ix_medidores_un_activo_por_servicio")
                        .IsUnique()
                        .HasDatabaseName("ix_medidores_servicio_id1")
                        .HasFilter("estado = 'Activo'");

                    b.ToTable("medidores", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("canton");

                    b.Property<string>("CedulaJuridica")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula_juridica");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provincia");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<int>("UltimoCorrelativoAbonado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ultimo_correlativo_abonado");

                    b.HasKey("Id")
                        .HasName("pk_organizaciones");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_organizaciones_codigo");

                    b.ToTable("organizaciones", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.HasKey("Id")
                        .HasName("pk_periodos");

                    b.HasIndex("OrganizacionId", "Anio", "Mes")
                        .IsUnique()
                        .HasDatabaseName("ix_periodos_organizacion_id_anio_mes");

                    b.ToTable("periodos", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonadoId")
                        .HasColumnType("integer")
                        .HasColumnName("abonado_id");

                    b.Property<string>("Canton")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("canton");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("Provincia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provincia");

                    b.Property<string>("Referencia")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("pk_propiedades");

                    b.HasIndex("AbonadoId")
                        .HasDatabaseName("ix_propiedades_abonado_id");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_propiedades_organizacion_id");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.SeguimientoLectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nota")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("nota");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id")
                        .HasName("pk_seguimientos_lectura");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_seguimientos_lectura_organizacion_id");

                    b.HasIndex("PeriodoId")
                        .HasDatabaseName("ix_seguimientos_lectura_periodo_id");

                    b.HasIndex("ServicioId", "PeriodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_seguimientos_lectura_servicio_id_periodo_id");

                    b.ToTable("seguimientos_lectura", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsMoroso")
                        .HasColumnType("boolean")
                        .HasColumnName("es_moroso");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("MensualidadesPendientes")
                        .HasColumnType("integer")
                        .HasColumnName("mensualidades_pendientes");

                    b.Property<decimal>("MontoPendiente")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_pendiente");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer")
                        .HasColumnName("propiedad_id");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_servicios_organizacion_id");

                    b.HasIndex("PropiedadId")
                        .HasDatabaseName("ix_servicios_propiedad_id");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Asada.Infraestructura.Identidad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Asada.Infraestructura.Identidad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("integer")
                        .HasColumnName("organizacion_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizacionId")
                        .HasDatabaseName("ix_usuarios_organizacion_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_rol_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rol_claims_role_id");

                    b.ToTable("rol_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_claims_user_id");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuario_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_logins_user_id");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuario_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_roles_role_id");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuario_tokens");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Abonado", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_abonados_organizaciones_organizacion_id");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Medicion", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Medidor", null)
                        .WithMany()
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_medidores_medidor_id");

                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_organizaciones_organizacion_id");

                    b.HasOne("Asada.Dominio.Entidades.Periodo", null)
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_periodos_periodo_id");

                    b.HasOne("Asada.Dominio.Entidades.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_servicios_servicio_id");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Medidor", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medidores_organizaciones_organizacion_id");

                    b.HasOne("Asada.Dominio.Entidades.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medidores_servicios_servicio_id");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Periodo", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_periodos_organizaciones_organizacion_id");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Propiedad", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Abonado", "Abonado")
                        .WithMany("Propiedades")
                        .HasForeignKey("AbonadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propiedades_abonados_abonado_id");

                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propiedades_organizaciones_organizacion_id");

                    b.Navigation("Abonado");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.SeguimientoLectura", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seguimientos_lectura_organizaciones_organizacion_id");

                    b.HasOne("Asada.Dominio.Entidades.Periodo", null)
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seguimientos_lectura_periodos_periodo_id");

                    b.HasOne("Asada.Dominio.Entidades.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seguimientos_lectura_servicios_servicio_id");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Servicio", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", null)
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_organizaciones_organizacion_id");

                    b.HasOne("Asada.Dominio.Entidades.Propiedad", "Propiedad")
                        .WithMany("Servicios")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicios_propiedades_propiedad_id");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Asada.Infraestructura.Identidad.Usuario", b =>
                {
                    b.HasOne("Asada.Dominio.Entidades.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_organizaciones_organizacion_id");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Asada.Infraestructura.Identidad.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Asada.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Asada.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Asada.Infraestructura.Identidad.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_roles_role_id");

                    b.HasOne("Asada.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Asada.Infraestructura.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Abonado", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("Asada.Dominio.Entidades.Propiedad", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
